### PR TITLE
chore: update map and reduce types

### PR DESCRIPTION
**Pull request by chasm**
I've been working through that TS course (one of them) and wanted to experiment.

What do you think? Better? I really hadn't used utility types much. Doh.

### CODE REVIEW

**Comment by chasm** [comment]
Just accept your changes on merge.

**Comment by benjstephenson** [comment]
I think this would reduce the type inferencing that occurs.  Because `MapFunction` takes no generic, the `F` parameter is still reduced to `(a: any) => any`
Screenshot 2024-04-06 at 17 02 40

 this forces us to explicitly type the function we pass to the `map` call:
Screenshot 2024-04-06 at 17 03 23

the knock on being that we can't pass a generic function without typing it also:
Screenshot 2024-04-06 at 17 04 58

**Comment by chasm** [comment]
Does it? Take a look at the array map and reduce test files here. We don't have to specify. But is this because everything is any? I must be doing something wrong because shouldn't it be looking at the type of the parameter(s) actually passed and the actual return type rather than the "type" passed?

**Comment by chasm** [comment]
It seems like there should be a way to do this without having to specify the types. No?

**Comment by benjstephenson** [comment]
Yep, in the array map test we get the f inferred as any.  
`Parameters<F>` does look at the parameters, but because `F` extends `(a: any) => any` we must fix the value `a`.  Type parameters are not passed "up" so to speak so  if we had

```ts
const id = <A>(a: A): A => a
declare const foo = map(id)
```
the `A` type parameter is not bound.

```ts
type Fn = <A>(a: A) => A
type B<F> = Fn extends MapFunction ? true : false

const a: B<Fn> //true

//this doesn't work because A is left free and so reduces to `unknown`
const params: Parameters<Fn> //[a: unknown]

//this works because the function parameters are of a fixed type
const numParams: Parameters<(a: number) => number> //[a: number]
```


This works: 
```ts
type MapFn<A, B> = (a: A) => B
type MapF =  <A, B>(f: MapFn<A, B>) => (arr: Array<Parameters<typeof f>[0]>) => Array<ReturnType<typeof f>>
const map: MapF = f => arr => arr.map(f)
const foo = pipe([1, 2, 3], map(a => a +1))
```
but all we've done is lift the definition of the f out from the `Map2`; I think it's much harder to read.

**Comment by chasm** [comment]
I knew it! Utility types are useless! :-P

I'll have to look at the example again. I thought it was working, but then I tried to get fancy.

**Comment by benjstephenson** [comment]
😆 I think of it as type parameters need to be filled in from the left.
Inferencing is done left to right and (I believe) not recursively unless
explicitly recursive through a mapped type.

**Pull request closed without merging**
