### PR TITLE
Merge my changes so we're on the same page

### PR DESCRIPTION
**Pull request by chasm**
So we're on the same page

### CODE REVIEW

**Comment by benjstephenson** [comment]
nice

**Comment by chasm** [comment]
Meh. I need to convert several to use `traverseArray`.

**Comment by chasm** [comment]
What do you want to work on (so we're not stepping on each other). I'm close to 100% test coverage, I think, so I might work on that. But there are a couple that probably just need to be deleted, e.g., `compareOperands`.

**Comment by benjstephenson** [comment]
I can rebase my other branch from main and update the remaining bits to use the `traverseAccumulate` implementation?

**Comment by chasm** [comment]
Deal.

**Pull request merged**
